site_name: FIWARE-IOT-Stack
site_url: https://github.com/telefonicaid/fiware-iot-stack/
repo_url: https://github.com/telefonicaid/fiware-iot-stack.git
site_description: IoT Platform document site
docs_dir: docs/
site_dir: html
markdown_extensions: [toc,tables, fenced_code]
use_directory_urls: false
theme: readthedocs
pages:
  - 'Introduction': 'index.md'
  - 'Getting Started': 'quickguide.md'
  - 'APIs':
    - 'Authentication API': 'authentication_api.md'
    - 'Device API': 'device_api.md'
    - 'Data API': 'data_api.md'
    - 'Historic Data API': 'historicdata_api.md'
    - 'Data Processing API': 'dataprocessing_api.md'
    - 'Management API': 'management_api.md'
  - 'Management Portal': 'portal.md'
  - 'Architecture': 
    - 'FIWARE Components': 'walkthrough.md'
    - 'Device Backend Gateway (IDAS)': 'device_gateway.md'
    - 'Context Broker (Orion)': 'context_broker.md'
    - 'Short Term Historic (STH)': 'sth.md'
    - 'Connector Framework (Cygnus)': 'cygnus.md'
    - 'Complex Event Processing (Perseo)': 'cep.md'
    - 'Identity Management (IDM)': 'idm.md'

