site_name: FIWARE-IOT-Stack
site_url: https://github.com/telefonicaid/fiware-iot-stack/
repo_url: https://github.com/telefonicaid/fiware-iot-stack.git
site_description: IoT Platform document site
docs_dir: docs/
site_dir: html
markdown_extensions: [toc,tables, fenced_code]
use_directory_urls: false
theme: readthedocs
pages:
  - 'Introduction': 'index.md'
  - 'APIs':
    - 'Authentication API': 'authentication_api.md'
    - 'Device API': 'device_api.md'
    - 'Data API': 'data_api.md'
    - 'Historical Data API': 'historicdata_api.md'
    - 'Complex Event Processing API': 'cep_api.md'
    - 'Management API': 'management_api.md'
  - 'Multitenancy: Service and Subservice': 'multitenancy.md'
  - 'Data persistence':
    - 'Naming conventions': 'naming_conventions.md'
  - 'Architecture':
    - 'FIWARE Components': 'walkthrough.md'
    - 'IoT Agents (IoTA)': 'device_gateway.md'
    - 'Context Broker (Orion)': 'context_broker.md'
    - 'Short Term Historic (STH)': 'sth.md'
    - 'Connector Framework (Cygnus)': 'cygnus.md'
    - 'Complex Event Processing (Perseo)': 'cep.md'
    - 'Security Components (IDM, PEP, AC)': 'security.md'
  - 'Topics':
    - 'Hadoop streaming with Hue': 'topics/hadoop_streaming_hue.md'
    - 'Character set limitations': 'topics/character_set_limitations.md'
    - 'How to send notifications': 'topics/how_notifications_work.md'
    - 'Geolocalized entities': 'topics/geolocalized_entities.md'
    - 'Subscriptions and registrations': 'topics/subcriptions_and_registrations.md'
    - 'Performance considerations': 'topics/performance_considerations.md'
    - 'Tips on how to model project entities': 'topics/modelling_considerations.md'
    - 'Quick start on device connection to the platform (with Ultralight 2.0)': 'topics/device_connection.md'
    - 'What is the best way to calculate a value based on Context changes': 'topics/data_calculation.md'
    - 'How to massively move data from/to the Platform (Big Data)': 'topics/move_big_data.md'
