site_name: FIWARE-IOT-Stack
site_url: https://github.com/telefonicaid/fiware-iot-stack/
repo_url: https://github.com/telefonicaid/fiware-iot-stack.git
site_description: IoT Platform document site
docs_dir: docs/
site_dir: html
markdown_extensions: [toc,tables, fenced_code]
use_directory_urls: false
theme: readthedocs
pages:
  - 'Introduction': 'index.md'
  - 'APIs':
    - 'Authentication API': 'authentication_api.md'
    - 'Device API': 'device_api.md'
    - 'Data API': 'data_api.md'
    - 'Historical Data API': 'historicdata_api.md'
    - 'Complex Event Processing API': 'cep_api.md'
    - 'Management API': 'management_api.md'
  - 'Multitenancy: Service and Subservice': 'multitenancy.md'
  - 'Data persistence':
    - 'Naming conventions': 'naming_conventions.md'
  - 'Architecture':
    - 'FIWARE Components': 'walkthrough.md'
    - 'IoT Agents (IoTA)': 'device_gateway.md'
    - 'Context Broker (Orion)': 'context_broker.md'
    - 'Short Term Historic (STH)': 'sth.md'
    - 'Connector Framework (Cygnus)': 'cygnus.md'
    - 'Complex Event Processing (Perseo)': 'cep.md'
    - 'Security Components (IDM, PEP, AC)': 'security.md'
  - 'Topics':
    - 'Hadoop streaming with Hue': 'topics/hadoop_streaming_hue.md'
